name: Find merge conflicts

on:
  pull_request:
    types: [ synchronize ]
  push:
    branches:
      - "main"

env:
  MERGE_CONFLICT: "error | merge conflict"


jobs:
  check_pr_open_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const { MERGE_CONFLICT } = process.env;
            
            async function getPullsNumber() {
              const prList = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "all",
              });

              const numberList = []
              prList.data.forEach((pr) => { numberList.push(pr.number) })
              return numberList
            }

            async function getPullDetails(pullNumbers) {
              const pullDetails = []
              pullNumbers.forEach(async (number) => {
                const pr = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: number,
                })

                if (pr.data.mergeable_state == "dirty") {
                  github.rest.issues.addLabels({
                    issue_number: number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: [MERGE_CONFLICT],
                  })
                }

              })
            }

            const pullsNumber = await getPullsNumber();
            getPullDetails(pullsNumber);
            setTimeout(getPullDetails, 20000, pullsNumber)
