name: Find merge conflicts

on:
  push:
    branches:
      - "main"

env:
  MERGE_CONFLICT: "error | merge conflict"


jobs:
  check_pr_open_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const { MERGE_CONFLICT } = process.env;
            
            async function getPullsNumber() {
              const prList = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
              });
              const numberList = []
              prList.data.forEach((pr) => { numberList.push(pr.number) })
              return numberList
            }

            async function getState(dict) {
              const prNumbers = Object.keys(dict);
              const promisesArr = [];
              for( let i = 0; i < prNumbers.length; i++){
                promisesArr.push(github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: Number(prNumbers[i]),
                }))
                
              }
              
              console.log(promisesArr)
              return promisesArr
            }
            
            const numbers = await getPullsNumber();
            var dict = {};
            numbers.forEach((e)=> {
                dict[e] = null;
            })
            console.log(await getState(dict))
            