name: Find merge conflicts

on:
  push:
    branches:
      - "main"

env:
  
  MERGE_CONFLICT: "error | merge conflict"
  

jobs:
  check_pr_open_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const prList = await github.rest.pulls.list({
                owner,
                repo,
                state: "all",
              });
              console.log(prList.data);
