name: Find merge conflicts

on:
  push:
    branches:
      - "main"

env:
  MERGE_CONFLICT: "error | merge conflict"


jobs:
  check_pr_open_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const { MERGE_CONFLICT } = process.env;
            
            async function getPullsNumber() {
              const prList = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
              });

              const numberList = []
              prList.data.forEach((pr) => { numberList.push(pr.number) })
              return numberList
            }
            
            async function addMergeConflictLabel(pullNumbers) {
              var myMap = new Map();
              const pullDetails = []
              pullNumbers.forEach(async (number) => {
                const pr = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: number,
                })
                myMap.set(number, pr.data.mergeable_state)
                
                if (pr.data.mergeable_state == "dirty") {
                  github.rest.issues.addLabels({
                    issue_number: number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: [MERGE_CONFLICT],
                  })
                }

              })
              return myMap;
            }

            const pullsNumber = await getPullsNumber();
            const myMap = addMergeConflictLabel(pullsNumber);
            for(let i = 0; i < 5; i++){
              
              for (const [key, value] of myMap.entries()) {
                if(value !== "unknown"){
                  myMap.delete(key);
                }
                
              }
              let newNumbers = Array.from(myMap.keys());
              setTimeout( 5000);
              const myMap = addMergeConflictLabel(newNumbers);
            }
           
            