name: Find merge conflicts

on:
  push:
    branches:
      - "main"

env:
  MERGE_CONFLICT: "error | merge conflict"


jobs:
  check_pr_open_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const { MERGE_CONFLICT } = process.env;
            
            async function getPullsNumber() {
              const prList = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "closed",
              });
              console.log(prList)

              const numberList = []
              prList.data.forEach((pr) => { numberList.push(pr.number) })
              return numberList
            }

            const numbers = await getPullsNumber();
            console.log(numbers)
